configurations:
 

  - run10:
      pretrain: True
      mini_batches: 4
      ratio_clip: 0.2
      learning_rate_scheduler: KLAdaptiveRL
      value_preprocessor: RunningStandardScaler

  - run11:
      pretrain: True
      mini_batches: 4
      ratio_clip: 0.5
      learning_rate_scheduler: KLAdaptiveRL
      value_preprocessor: RunningStandardScaler

