configurations:
### PPO
  - run1:
      entropy_loss_scale: 0.001
      learning_rate: 0.0005
      ratio_clip: 0.2

  - run2:
      entropy_loss_scale: 0.001
      learning_rate: 0.0005
      ratio_clip: 0.1

  - run3:
      entropy_loss_scale: 0.001
      learning_rate: 0.0005
      ratio_clip: 0.05

  - run4:
      entropy_loss_scale: 0.001
      learning_rate: 0.0005
      ratio_clip: 0.2
      kl_threshold: 0.016

  - run5:
      entropy_loss_scale: 0.001
      learning_rate: 0.001
      ratio_clip: 0.2

