configurations:
  - run1:
      pretrain: False
      mini_batches: 4

  - run2:
      pretrain: False
      mini_batches: 4
      value_preprocessor: RunningStandardScaler

  - run3:
      pretrain: False
      mini_batches: 4

  - run4:
      pretrain: False
      mini_batches: 4
      value_preprocessor: RunningStandardScaler

