configurations:
  - run1:
      pretrain: False
      mini_batches: 4

  - run2:
      pretrain: False
      mini_batches: 4
      value_preprocessor: RunningStandardScaler

  - run3:
      pretrain: True
      mini_batches: 4

  - run4:
      pretrain: True
      mini_batches: 4
      value_preprocessor: RunningStandardScaler

  - run5:
      pretrain: True
      mini_batches: 4
      lambda_0: 1.

  - run6:
      pretrain: True
      mini_batches: 4
      value_preprocessor: RunningStandardScaler
      lambda_0: 1.

