configurations:

  - run1:
      pretrain: False
      mini_batches: 4

  - run2:
      pretrain: False
      mini_batches: 4
      value_preprocessor: RunningStandardScaler

  - run3:
      pretrain: True
      mini_batches: 4

  - run4:
      pretrain: True
      mini_batches: 4

  - run5:
      pretrain: True
      mini_batches: 4

  - run6:
      pretrain: True
      mini_batches: 4

  - run7:
      pretrain: True
      mini_batches: 4
      value_preprocessor: RunningStandardScaler

  - run8:
      pretrain: True
      mini_batches: 4
      value_preprocessor: RunningStandardScaler

  - run9:
      pretrain: True
      mini_batches: 4
      value_preprocessor: RunningStandardScaler

  - run10:
      pretrain: True
      mini_batches: 4
      value_preprocessor: RunningStandardScaler

  - run11:
      pretrain: True
      mini_batches: 4
      lambda_0: 1.
      lambda_1: 0.999

  - run12:
      pretrain: True
      mini_batches: 4
      value_preprocessor: RunningStandardScaler
      lambda_0: 1.
      lambda_1: 0.999

  - run13:
      pretrain: True
      mini_batches: 4
      lambda_0: 1.
      lambda_1: 0.9999

  - run14:
      pretrain: True
      mini_batches: 4
      value_preprocessor: RunningStandardScaler
      lambda_0: 1.
      lambda_1: 0.9999

  - run15:
      pretrain: True
      mini_batches: 4
      lambda_0: 0.5
      lambda_1: 0.9999

  - run16:
      pretrain: True
      mini_batches: 4
      value_preprocessor: RunningStandardScaler
      lambda_0: 0.5
      lambda_1: 0.9999

  - run17:
      pretrain: True
      mini_batches: 4
      lambda_0: 0.5
      lambda_1: 0.99

  - run18:
      pretrain: True
      mini_batches: 4
      value_preprocessor: RunningStandardScaler
      lambda_0: 0.5
      lambda_1: 0.99


